### ISSUE TITLE
Question about how win_min_distance

### ISSUE THREAD

**Issue by pmagaz** [tungli/find_peaks-rs#3] opened 2022-04-28 06:27 UTC
Hi,

I'm [using](https://github.com/tungli/find_peaks-rs/issues/2) your library for technical analysis of the stock market and I use it for detection of local maxima/minima. Everything looks fine but I've detected several cases using with_min_distance in that the peaks returned are not the highest ones. In the image bellow you will see stock candles (white and blue) on a chart and the small blue triangles are the peaks returned by your library using win_min_distanance of 5. 

<img width="183" alt="image" src="https://user-images.githubusercontent.com/7657812/165569028-8f6d2345-8a7c-42db-97b2-812bb0f6e3cc.png">

As you can see the 3 biggest candles on the area were not  marked as peaks/local maxima. Is this a bug? 

Thanks.

**Comment by tungli** [comment] 2022-04-29 08:59
Hi Pablo,
thanks for letting me know - it certainly looks like a bug. I should be able to fix it during the weekend.
If you could send me the data set you are using, it would be very helpful.
Thanks!

**Comment by pmagaz** [comment] 2022-05-02 10:06
Hi.

Here it is. It's the [OHLC](https://en.wikipedia.org/wiki/Open-high-low-close_chart#:~:text=An%20open%2Dhigh%2Dlow%2D,one%20day%20or%20one%20hour.) price for the oil in 2022 and I used the High value (second field) for local maxima. The 3 highest peaks you see on the screenshot are the ones from 7 March to 9 March of 2022. 

I can't confirm but I have the feeling that the same issue could also happen without using with_min_distance.

[oil.csv](https://github.com/tungli/find_peaks-rs/files/8602129/oil.csv)

Regards

**Comment by tungli** [comment] 2022-05-02 21:10
Should be fixed with f5b8660494

I uploaded the fix to crates as well (version 0.1.4). Please @pmagaz verify that the issue is fixed for you to close this issue. Thanks! :)

**Comment by pmagaz** [comment] 2022-05-04 06:24
Hi,

I already tested and somehow the behavior has changed.

Here you have the output with version 1.0.3 without win_min_distance and as you can see there are 3 peaks (local maxima) before the big one
![oil_1 0 3](https://user-images.githubusercontent.com/7657812/166631493-d5f520c4-8871-4638-bb03-e821215b7b8a.png)

In version 1.0.4 using several values for min distance (5, 1, etc) the first two peaks and the last one at the right  are not identified:
![oil_1 0 4](https://user-images.githubusercontent.com/7657812/166631659-cdfa766f-3dfb-44f0-abd1-a7cd74a850cf.png)

I just wanna make sure I fully understand this parameter (not an expert in maths at all). The min distance is the distance between peaks right?

Regards

**Comment by tungli** [comment] 2022-05-18 09:38
@pmagaz  Sorry about the delay. Yes, there was still a bug in my implementation. Now is should be fixed.

See the added [oil example](https://github.com/tungli/find_peaks-rs/blob/master/examples/oil.rs) where I compare with scipy's `find_peaks` directly.

Distance filtering should always keep the highest peak possible - it first sorts based on peak height, than it removes  the peaks that are too close to the highest peak, then for the second highest, etc.

**Comment by pmagaz** [comment] 2022-05-18 09:54
No worries at all!. Your library is really useful for me. I'm not very good at maths XD and I'd say that maybe there is something you can help me with to give some clues. Local maxima/minima detection works fine when there is no big distance between peaks, or in my case prices. In the graphs that I shared with you it works fine because they are kind of 1/2 years graph and, in the case of the oil, there are no very big price movements therefore the difference between the minimum price and the max one is fine. The problem comes when you go to a graph of 4/5 years and stocks in that there was a huge price increase (eg: Bitcoin) as you can see in the image. In that case, the peaks on the left are usually not detected even if they are big but the ones on the right side are so big that make the others really small.

![image](https://user-images.githubusercontent.com/7657812/169010576-da0b234b-6b00-48b2-b921-a60a0218a61b.png)

The approach I was following to calculate the desired value for with_min_distance based on the difference between the max and min price (multiplied by another number) as minimum threshold and it works fine for assets with low/medium volatility but not for others with high volatility like bitcoin. 

Any advice?

Thanks in advance!

**Comment by tungli** [comment] 2022-05-19 14:07
Or one additional after thought - you could manipulate the data mathematically, for example doing a logarithm of the prices, and only them finding peaks.

![bitcoin logarithm](https://user-images.githubusercontent.com/33368331/169313479-06c558f3-1d61-4e13-8d24-cb6ea106f6af.png)

```rust
use find_peaks::PeakFinder;

use std::fs::File;
use std::io::prelude::*;

use pyo3::prelude::*;
use pyo3::types::IntoPyDict;

fn read_file(path: &str) -> std::io::Result<String> {
    let mut file = File::open(path)?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;
    Ok(contents)
}


fn main() -> Result<(), ()> {
    Python::with_gil(|py| {
        main_(py).map_err(|e| {
            // We can't display Python exceptions via std::fmt::Display,
            // so print the error here manually.
            e.print_and_set_sys_last_vars(py);
        })
    })
}
fn main_(py: Python) -> PyResult<()> {
    let data: Vec<f64> = read_file("data/bitcoin.dat")
        .expect("File not read!")
        .as_str()
        .split_whitespace()
        .map(|x| x.parse::<f64>().unwrap().ln())
        .collect();

    let prom = 0.1;
    let dist = &100;

    let mut fp = PeakFinder::new(&data);
    fp.with_min_prominence(prom);
    fp.with_min_distance(*dist);

    let peaks = fp.find_peaks();

    let x: Vec<usize> = peaks.iter().map(|x| x.middle_position()).collect();
    let y: Vec<f64> = x.iter().map(|x| data[*x]).collect();
    println!("{:?}", x);

    let plt = PyModule::import(py, "matplotlib.pyplot")?;
    plt.call1("plot", (data,))?;
    plt.call1("plot", (x.clone(), y.clone(), "g*"))?;
    plt.call0("show")?;


    Ok(())
}
```

**Comment by pmagaz** [comment] 2022-05-19 14:26
Thanks for your support in this!. The real problem is that I'm using this for a wide variety of instruments (stocks, cryptos, etc), and taking into account the significant differences between them (some of them could have a price of just 1$ and others 60.000$ like Bitcoin) I can't use any fixed prominence as you did in your example using ` let prom = 2000.;`. Somehow prominence should be related to the price  of the instrument itself (or something better) so so far my approach was something like this:

`let min_prominence = (max_price - min_price) * 0.025;`

As you said, following that approach only splitting the data into small chunks before finding peaks would work but what you did in your last example looks interesting but I'm not sure I'm understanding what you are doing in there to be able to use     `let prom = 0.1;` Sorry if I'm missing something but would you mind explaining it? 

Thanks in advance!

**Comment by tungli** [comment] 2022-05-19 14:53
@pmagaz Sure - the last example is making use of the [`ln` method](https://doc.rust-lang.org/std/primitive.f64.html#method.ln) of `f64` which is the natural logarithm. A logarithm is a function that maps a number to its order of magnitude. For example logarithm (of base 10) maps like this:
* log(1) = 0
* log(10) = 1
* log(1000) = 3
etc.

Of course, for the logarithm case the prominence will have to be different, since now the numbers are different.

To map back to the original prices you can use the exponential function:

```rust
let a: f64 = 21.     // some number
a.ln().exp() == a
```

**Comment by pmagaz** [comment] 2022-05-22 09:30
Hi. 

The logarithmic scale actually solved my issue!. I tried to use it in the past but it didn't work (probably I missed the second part to map back to the original prices). Regarding the issue of with_min_distance, I haven't detected anything weird so I'd say the bug is gone :) 

Thanks for your support!

:)

**Closed** 2022-05-22 09:30 UTC
